# Generated by Django 3.1.2 on 2020-10-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20201021_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
