# Generated by Django 3.1.2 on 2020-10-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='biography',
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_facts',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
