# Generated by Django 3.1.2 on 2020-10-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_auto_20201026_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_facts',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
